### PR TITLE
addRecipe and removeRecipe for Blood Magic Altar, Soulforge (Hellfire Forge) and Alchemy Table.

### PR DESCRIPTION
**Pull request by pobiega**
Pretty basic but works for both adding and removal for all three.

### CODE REVIEW

**Comment by pobiega** [comment]
Wiki page for bloodmagic

== Handlers Supported ==

The following handlers are supported:
* Soul Forge (Hellfire Forge)
* Ritual Altar
* Alchemy Table

Each of these handlers can have recipes added or removed: 


 //Soul Forge (Hellfire Forge)
 //Output, minimum souls, drain, input list
 mods.bloodmagic.SoulForge.addRecipe(<minecraft:diamond>,1,1,[<minecraft:cobblestone>]);
 //Output
 mods.bloodmagic.SoulForge.removeRecipe(<bloodmagic:ItemSlate>);

 
 //Ritual Altar
 //Output, minimum tier, syphon, consume rate, drain rate, input list
 mods.bloodmagic.Altar.addRecipe(<minecraft:diamond>,1,1,1,1,[<minecraft:cobblestone>]);
 //Output
 mods.bloodmagic.Altar.removeRecipe(<bloodmagic:ItemSlate>);

 //Alchemy Table
 //Output, lp drained, ticks required, tier required, input list
 mods.bloodmagic.AlchemyTable.addRecipe(<minecraft:diamond>,1,1,1,1,[<minecraft:cobblestone>]);
 //Output
 mods.bloodmagic.AlchemyTable.removeRecipe(<bloodmagic:ItemSlate>);

**Comment by Yulife** [comment]
Nice work! Have you thought about the Binding Ritual? @WayOfTime what else could be added?

**Comment by pobiega** [comment]
I have looked at AlchemyArray but couldn't come up with a good way to do it since the recipes include resource locations and alchemyeffects. Would need to make it so they can be created via zenscript first. With Ways help I'm sure we can figure something out.

**Comment by WayofTime** [comment]
I'm not very good at this sort of thing :D If you have a string as one of the inputs, say "bloodmagic:textures/models/AlchemyArrays/NewArray.png" and make a ResourceLocation from that, I guess you could have the person provide a resource pack to be used with whatever pack they are making.

**Comment by jaredlll08** [comment]
The resource locations can just be created as needed, have the user pass in
a string, and create the RL from that.

**Comment by jaredlll08** [comment]
Or even just use resourceloader, or a default image? I'm not sure how you
do things, but I'm sure you could just link to a default blood magic array
image?

On Oct 22, 2016 10:49 PM, "WayofTime" <notifications@github.com> wrote:

I'm not very good at this sort of thing :D If you have a string as one of
the inputs, say "bloodmagic:textures/models/AlchemyArrays/NewArray.png" and
make a ResourceLocation from that, I guess you could have the person
provide a resource pack to be used with whatever pack they are making.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jaredlll08/ModTweaker/pull/379#issuecomment-255553150>,
or mute the thread

**Pull request merged**
