### PR TITLE
Add support for adding BWM pulley blocks

### PR DESCRIPTION
**Pull request by democat3457**

### CODE REVIEW

**Comment by democat3457** [comment]
@jaredlll08 ready for review

**Comment by jaredlll08** [comment]
Is it possible to remove pulley blocks?

**Comment by democat3457** [comment]
no, thatd require a BWM update on their side - currently it functions similarly to the BWMHeatRegistry

**Comment by jaredlll08** [comment]
as per usual remind me to actually release it

**Pull request merged**
