### PR TITLE
Add Pyrolysis methods to Redstone Furnace

### PR DESCRIPTION
**Pull request by tgstyle**
Tested with 

mods.thermalexpansion.RedstoneFurnace.removeRecipePyrolysis(<minecraft:coal>);
mods.thermalexpansion.RedstoneFurnace.addRecipePyrolysis(<minecraft:redstone>, <minecraft:coal>, 3000, 250);

### CODE REVIEW

**Comment by jaredlll08** [comment]
Please use the standard convention for method names:
`removeRecipePyrolysis` -> `removePyrolysisRecipe`

**Comment by tgstyle** [comment]
Changed and commit is updated.

**Comment by jaredlll08** [comment]
sorry it took me so long to get back to this, can you change this line:
https://github.com/jaredlll08/ModTweaker/pull/564/files#diff-c8d305be86064c29b9130d6705a8fd07R122
to say it is a pyrolysis recipe please :)

**Comment by tgstyle** [comment]
Should be good to go, it now matches what others say for missing recipes of a type.

**Comment by jaredlll08** [comment]
thanks!

**Pull request merged**
