### PR TITLE
added Immersive Tech support

### PR DESCRIPTION
**Pull request by SanAndreaP**
PS: I've added Immersive Tech to the libs folder manually, as when I tried to use the maven link, gradle errors with a ZipExeption upon setupDecompWorkspace

### CODE REVIEW

**Comment by jaredlll08** [comment]
Why are you adding the jar file for immersive tech when you have the curseforge maven?

Why are you adding the CurseForge maven? IE is hosted on my maven (only new maven dep you added)

 https://maven.blamejared.com/blusunrize/ImmersiveEngineering/

**Comment by SanAndreaP** [comment]
I've added the PS on why the jar file in the above comment

I didn't know that IE is hosted on your maven, I'll fix that.

**Comment by kindlich** [comment]
There is already a PR for ImmersiveTech to add CrT support on their end.
Maybe there would be a better fit, maybe you can help them out there as well?

Also, since the ZenClass annotations have the same name argument, if both were to be added there would be conflicts, so keep that in mind as well.

The PR on their end:
https://github.com/FerroO2000/Immersive-Tech/pull/84

**Comment by SanAndreaP** [comment]
The problem with that PR is that it's not only adding CT support, but is also reworking some of the machines and stuff.

Also their github is outdated as of now (the github version is 1.3.9, from around a year ago, whereas CurseForge has 1.3.10), so their PR most likely won't be merged anytime soon.

**Pull request merged**
