### PR TITLE
It's building!

### PR DESCRIPTION
**Pull request by democat3457**
Fix build using cursemaven
I know you don't like using cursemaven, but in the meantime, this can be used for building.

### CODE REVIEW

**Comment by democat3457** [comment]
It also fixes warnings now and successfully builds, so that's good as well. @jaredlll08 review?

**Comment by democat3457** [comment]
(Also do I have to ping you for every pull request I make?)

**Comment by jaredlll08** [comment]
Player's maven is up, as well as a backup at `https://maven2.ic2.player.to/`, would prefer to use those for stuff they serve to be honest.

Also all of these PRs do the same thing since they are based on the same branch, so that needs to be cleaned up lol

**Comment by democat3457** [comment]
True lol, I was hoping this would get merged first

**Comment by democat3457** [comment]
Player's maven has been added.

**Pull request merged**
