### PR TITLE
Fix adding forestry recipes

### PR DESCRIPTION
**Pull request by laod**
This makes adding forestry recipes work again. Recipe changes are NOT properly reflected in JEI, however. I will look at that if I have time.

If I had to guess at why the reflection-based code in forestryHelper wasn't working I'd point to the fact that forestry uses HashSet instead of a list subtype, but my java is very rusty.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Thanks for the PR! I was saw what you were doing, was wondering when the PR would come :)

**Comment by laod** [comment]
Glad to help in some small way. Thanks for the mods. It wouldn't be possible to make interesting modpacks without them.

I took a little bit of a look to see if I could easily fix the added forestry recipes not showing up in JEI but I wasn't able to see anything obvious. I'll try and dig into it over the weekend.

**Comment by laod** [comment]
Disclaimer: all of this is only slightly better than speculation, given my lack of familiarity with JEI and Forestry.

At this point I'm fairly confident the only time forestry adds recipes to JEI is when it's JEIPlugins are loaded. I think I would have to reimplement all of forestry's factory JEI classes unless it's possible to tie my own recipe wrappers to Forestry's categories. Might try that.

**Comment by jaredlll08** [comment]
So what needs to doing is this line:
https://github.com/jaredlll08/ModTweaker/blob/master/src/main/java/modtweaker/mods/bloodmagic/handlers/Altar.java#L103
So that JEI's list can get updated

**Comment by laod** [comment]
https://github.com/jaredlll08/ModTweaker/blob/master/src/main/java/modtweaker/mods/forestry/ForestryListAddition.java#L28

**Comment by laod** [comment]
My intention wasn't to waste your time chasing things because of my confusion, so I probably should have waited to comment. I did try to understand why the call you're suggesting doesn't seem to work and given how unlikely what I'm investigating is to help, I should probably switch back to that.

**Comment by laod** [comment]
Hah! Found a hacky fix:

Moved the MineTweakerAPI.getIjeiRecipeRegistry().addRecipe() call to the handlers and then directly invoked forestry's wrapper constructor. So much for package boundaries. Wish they'd expose something via their api, but I can't find it.

Example from /src/main/java/modtweaker/mods/forestry/handlers/Squeezer.java:50:

MineTweakerAPI.getIjeiRecipeRegistry().addRecipe(new SqueezerRecipeWrapper(recipe));

**Comment by laod** [comment]
Hack in context: https://github.com/laod/ModTweaker/commit/468a626aa4498f79f0cc6575e89fbff02e0a202b

**Comment by jaredlll08** [comment]
that hack may not work, since if the user deletes the line in the script, and then runs /mt reload the recipe will still show, even though it doesn't exist

**Pull request merged**
