### PR TITLE
Improve forestry recipe JEI behavior. Moistener still broken.

### PR DESCRIPTION
**Pull request by laod**
This makes Forestry recipe changes show up in JEI again.

This is a more comprehensive hack. I feel better about it but it still reaches into the Forestry code more than I like and I don't feel confident that adding the wrapRecipe method to the ForestryList* interfaces was the best call, but I'm having trouble doing better.

### CODE REVIEW

**Comment by laod** [comment]
I should have squashed those commits. Sorry.

**Comment by SOL3675** [comment]
This mod has no update about 2 months, so I tried your changes in my environment.
It shows my custom carpenter's recipes correctly.
I'm looking forward to merge this code...

Here's my screenshot.
http://i.imgur.com/PHRCHSK.png

**Comment by jaredlll08** [comment]
I totally missed this PR O_o I'll do my own tests now

**Comment by jaredlll08** [comment]
Seems to work, thanks!

**Pull request merged**
